version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: 
- Any CPU
- x86
build:
  project: ExampleCIProject.sln
  verbosity: minimal
before_build:
- cmd: ls
- cmd: msbuild ExampleCIProject.sln /t:Restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: ExampleCIProject\bin\Release\ExampleCIProject.dll
  name: CompiledDll_Anycpu
- path: ExampleCIProject\bin\x86\Release\ExampleCIProject.dll
  name: CompiledDll_x86

deploy:
  release: ExampleCIProject-v$(APPVEYOR_BUILD_VERSION)
  description: '1'
  provider: GitHub
  auth_token:
    secure: "/kG4nHpHn+uY2utcG0DAufaHgRD/zrgrVRgZr/ogfljoLmGhHs3D8ARr/cENAoWJ"
  artifact:
    - "ExampleCIProject\bin\Release\ExampleCIProject.dll"
    - "ExampleCIProject\bin\x86\Release\ExampleCIProject.dll"
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

after_build:
- cmd: echo %cd%
- ps: ls -Recurse