version: '{build}'
image: Visual Studio 2017
configuration: Release

environment:
  appveyor_repo_tag: true

platform: 
- Any CPU
- x86
build:
  project: ExampleCIProject.sln
  verbosity: minimal
before_build:
- cmd: ls
- cmd: msbuild ExampleCIProject.sln /t:Restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: ExampleCIProject\bin\Release\ExampleCIProject.dll
  name: CompiledDll_Anycpu
- path: ExampleCIProject\bin\x86\Release\ExampleCIProject.dll
  name: CompiledDll_x86

deploy:
- provider: GitHub
  tag: release-$(APPVEYOR_BUILD_VERSION)
  description: "ExampleCIProject Release version=$(APPVEYOR_BUILD_VERSION)"
  auth_token:
    secure: /kG4nHpHn+uY2utcG0DAufaHgRD/zrgrVRgZr/ogfljoLmGhHs3D8ARr/cENAoWJ
  on:
    branch: master
    appveyor_repo_tag: true

after_build:
- cmd: echo %cd%
- ps: ls -Recurse