version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: ExampleCIProject.sln
  verbosity: minimal
before_build:
- cmd: ls
- cmd: msbuild ExampleCIProject.sln /t:Restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: appveyor.yml
- path: exampleciproject\ExampleCIProject\bin\Release\ExampleCIProject.dll
  name: CompiledDll

after_build:
- cmd: echo %cd%
- ps: ls -Recurse
- cmd: move .\exampleciproject\ExampleCIProject\bin\Release\ExampleCIProject.dll .\
- cmd: ls