version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: 
- Any CPU
- x86
build:
  project: ExampleCIProject.sln
  verbosity: minimal
before_build:
- cmd: ls
- cmd: msbuild ExampleCIProject.sln /t:Restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: ExampleCIProject\bin\Release\ExampleCIProject.dll
  name: CompiledDll_Anycpu
- path: ExampleCIProject\bin\x86\Release\ExampleCIProject.dll
  name: CompiledDll_x86

after_build:
- cmd: echo %cd%
- ps: ls -Recurse